name: EpicRename
main: com.gmail.justbru00.epic.rename.main.v3.Main
version: 3.9
description: Performs different item modifications with easy to use commands.
authors: [Justin Brubaker,JustBru00,jayoevans]
softdepend: [Vault]
api-version: 1.13

commands:
  rename:
    description: Renames items.
    aliases: [eprename]
  lore:
    description: Relores any item.   
    aliases: [eplore]
  epicrename:
    description: Plugin information command.
    aliases: [epepicrename]
  setloreline:
    description: Sets a certain line of lore.
    aliases: [epsetloreline,sll]
  removeloreline:
    description: Remove a line of lore.     
    aliases: [epremoveloreline,rll]
  insertloreline:
    description: Insert a certain line of lore.
    aliases: [epinsertloreline,ill]
  glow:
    description: Adds an enchantment glow.  
    aliases: [epglow]
  removeglow:
    description: Removes an enchantment glow.     
    aliases: [epremoveglow]     
  import:
    description: Imports items from a URL.
    aliases: [epimport]
  export:
    description: Exports items to EpicRenameOnline.
    aliases: [epexport]    
    
permissions:
  epicrename.epicrename:
    description: Basic permission for the /epicrename command.
  epicrename.epicrename.reload:
    description: Allows /epicrename reload. This will allow the user to reload the config.yml and messages.yml file.
  epicrename.epicrename.debug:
    description: Allows /epicrename debug.  This will allow the use to turn EpicRename debug mode on and off. This will cause many messages to spam in chat and is only recommended for diagnosing issues with EpicRename.
  
  epicrename.rename:
    description: Basic permission for the /rename command.  
  epicrename.rename.material.MATERIAL_HERE:
    description: Placeholder permission. Use an actual bukkit material for this permission to work. Ex. epicrename.rename.material.STONE
  epicrename.rename.material.*:
    description: Allows all materials for the /rename command.
  epicrename.rename.format.a:
    description: Permission for the color code a. 
  epicrename.rename.format.b:
    description: Permission for the color code b.  
  epicrename.rename.format.c:
    description: Permission for the color code c.    
  epicrename.rename.format.d:
    description: Permission for the color code d.   
  epicrename.rename.format.e:
    description: Permission for the color code e.   
  epicrename.rename.format.f:
    description: Permission for the color code f.   
  epicrename.rename.format.0:
    description: Permission for the color code 0.
  epicrename.rename.format.1:
    description: Permission for the color code 1.  
  epicrename.rename.format.2:
    description: Permission for the color code 2.  
  epicrename.rename.format.3:
    description: Permission for the color code 3.  
  epicrename.rename.format.4:
    description: Permission for the color code 4.  
  epicrename.rename.format.5:
    description: Permission for the color code 5.  
  epicrename.rename.format.6:
    description: Permission for the color code 6.  
  epicrename.rename.format.7:
    description: Permission for the color code 7.  
  epicrename.rename.format.8:
    description: Permission for the color code 8.  
  epicrename.rename.format.9:
    description: Permission for the color code 9.  
  epicrename.rename.format.hex:
    description: Permission for any hex color code.  
  
  epicrename.lore:
    description: Basic permission for the /lore command.  
  epicrename.lore.material.MATERIAL_HERE:
    description: Placeholder permission. Use an actual bukkit material for this permission to work. Ex. epicrename.lore.material.STONE
  epicrename.lore.material.*:
    description: Allows all materials for the /lore command.
  epicrename.lore.format.a:
    description: Permission for the color code a. 
  epicrename.lore.format.b:
    description: Permission for the color code b.  
  epicrename.lore.format.c:
    description: Permission for the color code c.    
  epicrename.lore.format.d:
    description: Permission for the color code d.   
  epicrename.lore.format.e:
    description: Permission for the color code e.   
  epicrename.lore.format.f:
    description: Permission for the color code f.   
  epicrename.lore.format.0:
    description: Permission for the color code 0.
  epicrename.lore.format.1:
    description: Permission for the color code 1.  
  epicrename.lore.format.2:
    description: Permission for the color code 2.  
  epicrename.lore.format.3:
    description: Permission for the color code 3.  
  epicrename.lore.format.4:
    description: Permission for the color code 4.  
  epicrename.lore.format.5:
    description: Permission for the color code 5.  
  epicrename.lore.format.6:
    description: Permission for the color code 6.  
  epicrename.lore.format.7:
    description: Permission for the color code 7.  
  epicrename.lore.format.8:
    description: Permission for the color code 8.  
  epicrename.lore.format.9:
    description: Permission for the color code 9.  
  epicrename.lore.format.hex:
    description: Permission for any hex color code.    
      
  epicrename.setloreline:
    description: Basic permission for the /setloreline command.  
  epicrename.setloreline.material.MATERIAL_HERE:
    description: Placeholder permission. Use an actual bukkit material for this permission to work. Ex. epicrename.setloreline.material.STONE
  epicrename.setloreline.material.*:
    description: Allows all materials for the /setloreline command.
  epicrename.setloreline.format.a:
    description: Permission for the color code a. 
  epicrename.setloreline.format.b:
    description: Permission for the color code b.  
  epicrename.setloreline.format.c:
    description: Permission for the color code c.    
  epicrename.setloreline.format.d:
    description: Permission for the color code d.   
  epicrename.setloreline.format.e:
    description: Permission for the color code e.   
  epicrename.setloreline.format.f:
    description: Permission for the color code f.   
  epicrename.setloreline.format.0:
    description: Permission for the color code 0.
  epicrename.setloreline.format.1:
    description: Permission for the color code 1.  
  epicrename.setloreline.format.2:
    description: Permission for the color code 2.  
  epicrename.setloreline.format.3:
    description: Permission for the color code 3.  
  epicrename.setloreline.format.4:
    description: Permission for the color code 4.  
  epicrename.setloreline.format.5:
    description: Permission for the color code 5.  
  epicrename.setloreline.format.6:
    description: Permission for the color code 6.  
  epicrename.setloreline.format.7:
    description: Permission for the color code 7.  
  epicrename.setloreline.format.8:
    description: Permission for the color code 8.  
  epicrename.setloreline.format.9:
    description: Permission for the color code 9.  
  epicrename.setloreline.format.hex:
    description: Permission for any hex color code.
    
  epicrename.removeloreline:
    description: Basic permission for the /removeloreline command.  
  epicrename.removeloreline.material.MATERIAL_HERE:
    description: Placeholder permission. Use an actual bukkit material for this permission to work. Ex. epicrename.removeloreline.material.STONE
  epicrename.removeloreline.material.*:
    description: Allows all materials for the /removeloreline command.  
    
  epicrename.insertloreline:
    description: Basic permission for the /insertloreline command.  
  epicrename.insertloreline.material.MATERIAL_HERE:
    description: Placeholder permission. Use an actual bukkit material for this permission to work. Ex. epicrename.insertloreline.material.STONE
  epicrename.insertloreline.material.*:
    description: Allows all materials for the /insertloreline command.
  epicrename.insertloreline.format.a:
    description: Permission for the color code a. 
  epicrename.insertloreline.format.b:
    description: Permission for the color code b.  
  epicrename.insertloreline.format.c:
    description: Permission for the color code c.    
  epicrename.insertloreline.format.d:
    description: Permission for the color code d.   
  epicrename.insertloreline.format.e:
    description: Permission for the color code e.   
  epicrename.insertloreline.format.f:
    description: Permission for the color code f.   
  epicrename.insertloreline.format.0:
    description: Permission for the color code 0.
  epicrename.insertloreline.format.1:
    description: Permission for the color code 1.  
  epicrename.insertloreline.format.2:
    description: Permission for the color code 2.  
  epicrename.insertloreline.format.3:
    description: Permission for the color code 3.  
  epicrename.insertloreline.format.4:
    description: Permission for the color code 4.  
  epicrename.insertloreline.format.5:
    description: Permission for the color code 5.  
  epicrename.insertloreline.format.6:
    description: Permission for the color code 6.  
  epicrename.insertloreline.format.7:
    description: Permission for the color code 7.  
  epicrename.insertloreline.format.8:
    description: Permission for the color code 8.  
  epicrename.insertloreline.format.9:
    description: Permission for the color code 9.  
  epicrename.insertloreline.format.hex:
    description: Permission for any hex color code.      
    
  epicrename.glow:
    description: Basic permission for the /glow command.  
  epicrename.glow.material.MATERIAL_HERE:
    description: Placeholder permission. Use an actual bukkit material for this permission to work. Ex. epicrename.glow.material.STONE
  epicrename.glow.material.*:
    description: Allows all materials for the /glow command.     
    
  epicrename.removeglow:
    description: Basic permission for the /removeglow command.  
  epicrename.removeglow.material.MATERIAL_HERE:
    description: Placeholder permission. Use an actual bukkit material for this permission to work. Ex. epicrename.removeglow.material.STONE
  epicrename.removeglow.material.*:
    description: Allows all materials for the /removeglow command.   
    
  epicrename.import:
    description: Allows access to the /import command. WARNING! This command allows the user to import ANY item they desire. This command should be reserved for server admins.
        
  epicrename.export:
    description: Allows access to the /export command. This command allows the player to export their items to be used on another server with EpicRename installed with just a link.
      
  epicrename.bypass.charlimit:
    description: Allows the user to bypass the character limit set for /rename.
  epicrename.bypass.materialblacklist:
    description: Allows the user to bypass the material blacklist.
  epicrename.bypass.textblacklist:
    description: Allows the user to bypass the text blacklist.
  epicrename.bypass.existingname:
    description: Allows the user to bypass the existing name blacklist.
  epicrename.bypass.existinglore:
    description: Allows the user to bypass the existing lore blacklist.
  
  epicrename.bypass.costs.rename:
    description: Allows the user to bypass the economy or experience cost set for /rename.
  epicrename.bypass.costs.lore:
    description: Allows the user to bypass the economy or experience cost set for /lore.
  epicrename.bypass.costs.glow:
    description: Allows the user to bypass the economy or experience cost set for /glow.
  epicrename.bypass.costs.*:
    description: Allows the user to bypass the economy or experience cost of ALL supported commands.
    
  epicrename.bypass.formattingcodemax:
    description: Allows the user to bypass the formatting code maximum setting.
  epicrename.bypass.formattingcodemin:
    description: Allows the user to bypass the formatting code minimum setting.        
  
  epicrename.rename.format.*:
    description: Allows all formatting codes for the /rename command.
    children:
      epicrename.rename.format.a: true
      epicrename.rename.format.b: true
      epicrename.rename.format.c: true
      epicrename.rename.format.d: true
      epicrename.rename.format.e: true
      epicrename.rename.format.f: true
      epicrename.rename.format.0: true
      epicrename.rename.format.1: true
      epicrename.rename.format.2: true
      epicrename.rename.format.3: true
      epicrename.rename.format.4: true
      epicrename.rename.format.5: true
      epicrename.rename.format.6: true
      epicrename.rename.format.7: true
      epicrename.rename.format.8: true
      epicrename.rename.format.9: true
      epicrename.rename.format.hex: true
      
  epicrename.lore.format.*:
    description: Allows all formatting codes for the /lore command.
    children:
      epicrename.lore.format.a: true
      epicrename.lore.format.b: true
      epicrename.lore.format.c: true
      epicrename.lore.format.d: true
      epicrename.lore.format.e: true
      epicrename.lore.format.f: true
      epicrename.lore.format.0: true
      epicrename.lore.format.1: true
      epicrename.lore.format.2: true
      epicrename.lore.format.3: true
      epicrename.lore.format.4: true
      epicrename.lore.format.5: true
      epicrename.lore.format.6: true
      epicrename.lore.format.7: true
      epicrename.lore.format.8: true
      epicrename.lore.format.9: true
      epicrename.lore.format.hex: true      

  epicrename.setloreline.format.*:
    description: Allows all formatting codes for the /setloreline command.
    children:
      epicrename.setloreline.format.a: true
      epicrename.setloreline.format.b: true
      epicrename.setloreline.format.c: true
      epicrename.setloreline.format.d: true
      epicrename.setloreline.format.e: true
      epicrename.setloreline.format.f: true
      epicrename.setloreline.format.0: true
      epicrename.setloreline.format.1: true
      epicrename.setloreline.format.2: true
      epicrename.setloreline.format.3: true
      epicrename.setloreline.format.4: true
      epicrename.setloreline.format.5: true
      epicrename.setloreline.format.6: true
      epicrename.setloreline.format.7: true
      epicrename.setloreline.format.8: true
      epicrename.setloreline.format.9: true
      epicrename.setloreline.format.hex: true 

  epicrename.insertloreline.format.*:
    description: Allows all formatting codes for the /insertloreline command.
    children:
      epicrename.insertloreline.format.a: true
      epicrename.insertloreline.format.b: true
      epicrename.insertloreline.format.c: true
      epicrename.insertloreline.format.d: true
      epicrename.insertloreline.format.e: true
      epicrename.insertloreline.format.f: true
      epicrename.insertloreline.format.0: true
      epicrename.insertloreline.format.1: true
      epicrename.insertloreline.format.2: true
      epicrename.insertloreline.format.3: true
      epicrename.insertloreline.format.4: true
      epicrename.insertloreline.format.5: true
      epicrename.insertloreline.format.6: true
      epicrename.insertloreline.format.7: true
      epicrename.insertloreline.format.8: true
      epicrename.insertloreline.format.9: true
      epicrename.insertloreline.format.hex: true
    
  epicrename.administrator:
    description: Provides the user permission for all materials and all formatting codes for all commands. Does not provide bypass permissions. Use epicrename.bypass.* for that.
    children:
      epicrename.epicrename: true
      epicrename.epicrename.reload: true
      epicrename.epicrename.debug: true
      epicrename.rename.*: true
      epicrename.lore.*: true
      epicrename.setloreline.*: true
      epicrename.removeloreline.*: true
      epicrename.insertloreline.*: true
      epicrename.glow.*: true
      epicrename.removeglow.*: true
      epicrename.import: true
      epicrename.export: true
      
  epicrename.poweruser:
    description: Provides the user permission for all materials and all formatting codes for all commands except for /import, /epicrename reload, or /epicrename debug. Does not provide bypass permissions. Use epicrename.bypass.* for that.
    children:
      epicrename.epicrename: true
      epicrename.rename.*: true
      epicrename.lore.*: true
      epicrename.setloreline.*: true
      epicrename.removeloreline.*: true
      epicrename.insertloreline.*: true
      epicrename.glow.*: true
      epicrename.removeglow.*: true
      epicrename.export: true
      
  epicrename.rename.*:
    description: Provides the user permission for all materials and all formatting codes for /rename. Also provides basic permission epicrename.rename.        
    children:
      epicrename.rename: true
      epicrename.rename.material.*: true
      epicrename.rename.format.*: true
      
  epicrename.lore.*:
    description: Provides the user permission for all materials and all formatting codes for /lore. Also provides basic permission epicrename.lore.
    children:
      epicrename.lore: true
      epicrename.lore.material.*: true
      epicrename.lore.format.*: true
      
  epicrename.setloreline.*:
    description: Provides the user permission for all materials and all formatting codes for /setloreline. Also provides basic permission epicrename.setloreline.           
    children:
      epicrename.setloreline: true
      epicrename.setloreline.material.*: true
      epicrename.setloreline.format.*: true
      
  epicrename.removeloreline.*:
    description: Provides the user permission for all materials for /removeloreline. Also provides basic permission epicrename.removeloreline.       
    children:
      epicrename.removeloreline: true
      epicrename.removeloreline.material.*: true
      
  epicrename.insertloreline.*:
    description: Provides the user permission for all materials and all formatting codes for /insertloreline. Also provides basic permission epicrename.insertloreline.
    children:
      epicrename.insertloreline: true
      epicrename.insertloreline.material.*: true
      epicrename.insertloreline.format.*: true
            
  epicrename.glow.*:
    description: Provides the user permission for all materials for /glow. Also provides basic permission epicrename.glow.       
    children:
      epicrename.glow: true
      epicrename.glow.material.*: true
      
  epicrename.removeglow.*:
    description: Provides the user permission for all materials for /removeglow. Also provides basic permission epicrename.removeglow.     
    children:
      epicrename.removeglow: true
      epicrename.removeglow.material.*: true
      
  epicrename.bypass.*:
    description: Provides the user permission to bypass all the things. Bypasses character limit, material blacklist, text blacklist, existing name blacklist, existing lore blacklist, all economy or experience costs, formatting code minimum, formatting code maximum.
    children:
      epicrename.bypass.charlimit: true
      epicrename.bypass.materialblacklist: true
      epicrename.bypass.textblacklist: true
      epicrename.bypass.existingname: true
      epicrename.bypass.existinglore: true
      epicrename.bypass.costs.*: true
      epicrename.bypass.formattingcodemax: true
      epicrename.bypass.formattingcodemin: true